### ISSUE TITLE
InvPT has been accepted by ECCV 2022

### ISSUE THREAD

**Issue by prismformore** [WeiHongLee/Awesome-Multi-Task-Learning#1]
Hi Wei-hong!

Thank you for your valuable awesome repo. 

May I kindly remind you that our paper **InvPT**: [Inverted Pyramid Multi-task Transformer for Dense Scene Understanding](https://arxiv.org/abs/2203.07997) has been accepted by ECCV 2022. We would appreciate it if you could include this modification in your next update.

Have a nice day.

Hanrong

**Comment by WeihongLi-ac** [comment]
Hi Hanrong,

Thank you for reminding me and congratulations on your paper!

I've updated the information about your paper.

Many thanks!
Wei-Hong

**Comment by prismformore** [comment]
@WeiHongLee It looks great! Thanks a lot : )
Hanrong
