### ISSUE TITLE
Addressing Negative Transfer in Diffusion Models (Neurips 2023)

### ISSUE THREAD

**Issue by gohyojun15** [WeiHongLee/Awesome-Multi-Task-Learning#2]
Hello Wei-hong!

Thank you for making and contributing a priceless repo!

I would like to inform you that our paper "Addressing Negative Transfer in Diffusion Models (Neurips 2023)" deals with harmonious learning of multiple denoising tasks in the diffusion model by rethinking it as multi-task learning. Will you consider including our paper in your repository? I believe that the MTL of denoising tasks is an important direction for improving the diffusion model, and I saw that our paper "Denoising Task Routing in Diffusion Models" is already included in your repo. 

Arxiv: https://arxiv.org/abs/2306.00354
OpenReview: https://openreview.net/forum?id=3G2ec833mW&referrer=%5Bthe%20profile%20of%20Shinhyeok%20Oh%5D(%2Fprofile%3Fid%3D~Shinhyeok_Oh1)
Code: https://github.com/gohyojun15/ANT_diffusion

I hope you have a nice day.

Hyojun Go

**Comment by WeihongLi-ac** [comment]
Hi Hyojun,

Many thanks for the suggested paper and congrats on the papers, which are very interesting to me! I have added the paper to the list and do let me know if you have any other interesting paper for multi-task learning. 

Best wishes,
Wei-Hong

**Comment by gohyojun15** [comment]
Thank you for your quick response!
Thanks a lot!
