### ISSUE TITLE
Adding BayesAgg-MTL

### ISSUE THREAD

**Issue by IdanAchituve** [WeiHongLee/Awesome-Multi-Task-Learning#4]
Hi,
Thanks for this wonderful repo!
We believe that our paper on MTL, which was accepted to ICML 2024, may be relevant here.
paper: https://arxiv.org/abs/2402.04005
code: https://github.com/ssi-research/BayesAgg_MTL

Thanks!
Idan

**Comment by WeihongLi-ac** [comment]
Hi,

Sorry for late reply as I was busy on some submissions. 

Sure, I have added your paper to the list and congrats on the paper! And please let me know if you find some interesting paper in MTL and your future work on MTL.

Thanks!
WH

**Comment by IdanAchituve** [comment]
Sure, thanks a lot! Good luck with the submissions as well!
