### ISSUE TITLE
Request to add more MTL papers

### ISSUE THREAD

**Issue by bhsimon0810** [WeiHongLee/Awesome-Multi-Task-Learning#5]
Hi,

Thanks for your awesome repo! We are a deep learning and optimization group, and we have two papers on multi-task learning.

- Direction-oriented Multi-objective Learning: Simple and Provable Stochastic Algorithms. [NeurIPS 2023][[paper](https://arxiv.org/abs/2305.18409)][[code](https://github.com/OptMN-Lab/sdmgrad)]

- Fair Resource Allocation in Multi-Task Learning. [ICML 2024][[paper](https://arxiv.org/abs/2402.15638)][[code](https://github.com/OptMN-Lab/fairgrad)]

Would you mind checking these papers and adding them to your list when you are available?

Best regards,
Hao Ban

**Comment by WeihongLi-ac** [comment]
Hi Hao,

Many thanks for the papers! I have just added them to the list!

Best wishes,
WH

**Comment by bhsimon0810** [comment]
Thanks! Close the issue :)
